name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change to your branch if necessary
  pull_request:
    branches:
      - main  # Change to your branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js version 16

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}  # Ensure your Firebase token is set in GitHub Secrets
